version: '3'

services:
  postgresql-master:
    image: 'bitnami/postgresql:11-centos-7'
    ports:
      - 5433:5432
    volumes:
      - 'postgresql_master_data:/bitnami'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=10
    volumes:
      - /Users/muhammadsoultani/Documents/code/dockercompose/master-slave/postgresql-data:/bitnami
      - /Users/muhammadsoultani/Documents/code/dockercompose/master-slave/postgresql-data/postgresql/conf:/bitnami/postgresql/conf
  postgresql-slave:
    image: 'bitnami/postgresql:11-centos-7'
    ports:
      - '5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - /Users/muhammadsoultani/Documents/code/dockercompose/master-slave/postgresql-data/postgresql/conf:/bitnami/postgresql/conf

networks:
  default:
    external:
      name: local-net
