version: '3'

services:

  # POSTGRESQL
  postgresql-master:
    image: 'bitnami/postgresql:11-centos-7'
    ports:
      - 5433:5432
    volumes:
      - 'postgresql_master_data:/bitnami'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=10
    volumes:
      - ${LOCAL_PATH}/dockercompose/master-slave/postgresql-data:/bitnami
      - ${LOCAL_PATH}/dockercompose/master-slave/postgresql-data/postgresql/conf:/bitnami/postgresql/conf

  postgresql-master-backup:
    image: 'bitnami/postgresql:11-centos-7'
    ports:
      - 5439:5432
    volumes:
      - 'postgresql_master_data:/bitnami'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=10
    volumes:
      - ${LOCAL_PATH}/dockercompose/master-slave/postgresql-data:/bitnami
      - ${LOCAL_PATH}/dockercompose/master-slave/postgresql-data/postgresql/conf:/bitnami/postgresql/conf


  postgresql-slave:
    image: 'bitnami/postgresql:11-centos-7'
    ports:
      - 5434-5435:5432
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ${LOCAL_PATH}/dockercompose/master-slave/postgresql-data/postgresql/conf:/bitnami/postgresql/conf

  #DEMO SERVICE
  demo-service:
    image: 'gcr.io/annular-catfish-250011/${SERVICE}:0.0.1-release'
    ports:
      - 8080:8080
    depends_on:
      - postgresql-slave
    env_file:
      - ./${DB}.env


networks:
  default:
    external:
      name: local-net
