version: '3'

services:

  # POSTGRESQL
  postgresql-master:
    image: 'bitnami/postgresql:11-centos-7'
    ports:
      - 5433:5432
    volumes:
      - 'postgresql_master_data:/bitnami'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=10
    volumes:
      - ${LOCAL_PATH}/dockercompose/master-slave/postgresql-data:/bitnami
      - ${LOCAL_PATH}/dockercompose/master-slave/postgresql-data/postgresql/conf:/bitnami/postgresql/conf
  postgresql-slave:
    image: 'bitnami/postgresql:11-centos-7'
    ports:
      - 5434-5435:5432
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ${LOCAL_PATH}/dockercompose/master-slave/postgresql-data/postgresql/conf:/bitnami/postgresql/conf

  #MYSQL
  mysql-master:
    image: 'bitnami/mysql:5.7'
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=my_repl_user
      - MYSQL_REPLICATION_PASSWORD=my_repl_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
    volumes:
      - ${LOCAL_PATH}/dockercompose/mysql-master-slave/data:/bitnami/mysql/data
      - ${LOCAL_PATH}/dockercompose/mysql-master-slave/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
  mysql-slave:
    image: 'bitnami/mysql:5.7'
    ports:
      - 3308-3309:3306
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=my_repl_user
      - MYSQL_REPLICATION_PASSWORD=my_repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
    volumes:
      - ${LOCAL_PATH}/dockercompose/mysql-master-slave/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro


  #MONGODB
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=my_password
      - MONGODB_DATABASE=my_database
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27018-27020:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      #- MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter

  #DEMO SERVICE
  demo-service:
    image: 'com.tix.template.demo.serviceApi/tix-demo-service-api-mongo:0.0.1-release'
    ports:
      - 8080:8080
    depends_on:
      - mysql-slave
      - postgresql-slave
      - mongodb-secondary
    env_file:
      - ./${DB}.env


networks:
  default:
    external:
      name: local-net
