version: '3'

services:
  tix-config-server:
    image: 'gcr.io/annular-catfish-250011/tix-config-server:0.0.1-release'
    ports:
      - 8888:8888

networks:
  default:
    external:
      name: local-net
