version: '3'
services:
  rabbitmq-server:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      default:
        aliases:
          - rabbitmq-server
networks:
  default:
    external:
      name: local-net
