version: '3'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=my_password
      - MONGODB_DATABASE=my_database
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary


  # mongodb-secondary:
  #   image: 'bitnami/mongodb:latest'
  #   ports:
  #     - 27018-27020:27017-27019
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_REPLICA_SET_MODE=secondary
  #     - MONGODB_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_PRIMARY_PORT_NUMBER=27017
  #     - MONGODB_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
  #
  # mongodb-arbiter:
  #   image: 'bitnami/mongodb:latest'
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_REPLICA_SET_MODE=arbiter
  #     - MONGODB_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_PRIMARY_PORT_NUMBER=27017
  #     - MONGODB_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter

networks:
  default:
    external:
      name: local-net
