version: '3'

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017-27019:27017-27019
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
