version: '3'

services:
  zookeeper-standalone:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper-standalone
    ports:
     - '2181'
     - 8081:8080
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ALLOW_ANONYMOUS_LOGIN=yes
      # - ZOO_SERVER_USERS=kafka
      # - ZOO_SERVER_PASSWORDS=kafka_password
  kafka-standalone:
    image: 'bitnami/kafka:latest'
    hostname: kafka-standalone
    depends_on:
      - zookeeper-standalone
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      - KAFKA_CFG_PORT=${KAFKA_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:${KAFKA_PORT}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT}
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-standalone:2181
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_INTER_BROKER_USER=interuser
      - KAFKA_INTER_BROKER_PASSWORD=interpassword
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=password
      - ALLOW_PLAINTEXT_LISTENER=true
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=30000

networks:
  default:
    external:
      name: local-net
