version: '3'
services:
  moka-service-payment:
    image: 055378290905.dkr.ecr.ap-southeast-1.amazonaws.com/moka-service-payment:test-include-newrelic
    env_file:
      - ${ENV}.env
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    ports:
      - 8080:8080
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup


networks:
  default:
    external:
      name: local-net
