version: '3'
services:
  rails-server:
    image: centos/systemd
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    ports:
      - 8080:80
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup


networks:
  default:
    external:
      name: local-net
